export const officeofpresident = [
//   {
//     photo: require("../../../public/images/Leadership photos/Keith-Nurse.jpeg"),
//     handle: "knurse",
//     altText: " photo Keith Nurse",
//     name: "Keith Nurse",
//     position: "President",
//     email: "knurse@costaatt.edu.tt",
//     phone: "1-868-625-5030 ext 0000",
//   },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "ccharles",
    altText: " photo Carlene Charles",
    name: "Carlene Charles",
    position: "Executive Assistant",
    email: "c@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 1111",
  },

  {
    photo: require("../../../public/images/Leadership photos/Rodney-Amar.jpg"),
    handle: "ramar",
    altText: " photo Rodney Amar",
    name: "Rodney Amar",
    position: "Senior Project Officer",
    email: "ramar@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "mheadly",
    altText: " photo Melissa Headley",
    name: "Melissa Headley",
    position: "Senior Project Officer",
    email: "mheadley@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Lisa-Solomon.jpg"),
    handle: "rsolomon",
    altText: " photo Lisa Solomon",
    name: "Lisa Solomon",
    position: "Corporate Secretary",
    email: "lsolomond@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },

  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "kmaharaj",
    altText: " photo Kavita Maharaj",
    name: "Kavita Maharaj",
    position: "Chief Internal Auditor ",
    email: "kmaharaj@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
];
export const vps = [
    {
      photo: require("../../../public/images/Leadership photos/Keith-Nurse.jpeg"),
      handle: "knurse",
      altText: " photo Keith Nurse",
      name: "Keith Nurse",
      position: "President",
      email: "knurse@costaatt.edu.tt",
      phone: "1-868-625-5030 ext 0000",
    },
  {
    photo: require("../../../public/images/Leadership photos/Naseem-Koylass.jpg"),
    handle: "ccharles",
    altText: " photo Naseem Koylass",
    name: "Naseem Koylass",
    position: "Vice President, Academic Affairs",
    email: "nkoylass@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 1111",
  },

  {
    photo: require("../../../public/images/Leadership photos/HelenWC_small.jpg"),
    handle: "hcumberbatch",
    altText: " photo Helen Cumberbatch",
    name: "Helen Williams-Cumberbatch",
    position: "Vice President, Student Affairs",
    email: "hcumberbatch@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Avenille-Matthew.jpg"),
    handle: "amatthew",
    altText: " photo Avenille Matthew",
    name: "Avenille Matthew",
    position: "Vice Presient,Human Resources ",
    email: "amatthew@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },


];

export const management = [
  {
    photo: require("../../../public/images/Leadership photos/Rhonda.jpg"),
    handle: "rcumberbatch",
    altText: " photo Rhonda",
    name: "Rhonda Cumberbatch",
    position: "College Registrar",
    email: "rcumberbatch@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 1111",
  },

  {
    photo: require("../../../public/images/Leadership photos/Liesel-Gransaull.jpg"),
    handle: "lbrown",
    altText: " photo Liesel Gransaull-Brown",
    name: "Liesel Gransuall-Brown",
    position: "Director,Education Technologies & Distance Education",
    email: "lbrown@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Dawn-Dookie.jpg"),
    handle: "ddookie",
    altText: " photo Melissa Headley",
    name: "Dwan Dookie",
    position: "Director, Finance",
    email: "ddookie@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Doodnath-Persad.jpg"),
    handle: "dpersad",
    altText: " photo Doodnath Persad",
    name: "Dr Doodnath Persad",
    position: "Director,Quality Assurance and Institutional Research",
    email: "dpersad@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },

  {
    photo: require("../../../public/images/Leadership photos/Marcia-Stanisclaus.jpg"),
    handle: "mstanisclaus",
    altText: " photo Marcia Stanisclaus",
    name: "Marcia Stanisclaus",
    position: "Director, Planning and Employment",
    email: "mstanisclaus@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "icarter",
    altText: " photo Ian Carter",
    name: "Ian Carter",
    position: "Director, Student Life & Athletics ",
    email: "kmaharaj@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "icarter",
    altText: " photo new Peson",
    name: "Soonita ???",
    position: "Director, Library Services",
    email: "soon@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
];

export const deans = [
  
  {
    photo: require("../../../public/images/Leadership photos/Lalita.jpg"),
    handle: "lramlal",
    altText: " photo Lalita",
    name: "Lalita Ramlal-Chirkoot",
    position: "Dean,Workforce",
    email: "c@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 1111",
  },

  {
    photo: require("../../../public/images/Leadership photos/Rodney-Amar.jpg"),
    handle: "ksantana",
    altText: " photo Kyra Santana",
    name: "Dr. Kyra Santana",
    position: "Dean, School of Business and Digial Technologies",
    email: "ramar@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "cjack",
    altText: " photo Clarinda Jack",
    name: "Clarinda Jack",
    position: "Dean,Ken Gordon School of Communication,Creative and Digital Media",
    email: "cjack@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Anjenney-Dwarika.jpg"),
    handle: "rsolomon",
    altText: " photo Anjenny Dwarika",
    name: "Anjenny Dwarika",
    position: "School of Nursing, Health and Medical Technologies",
    email: "adwarika@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },

  {
    photo: require("../../../public/images/Leadership photos/Delamae-Wilson.jpg"),
    handle: "Delamae Wilson",
    altText: " photo Delamae Wilson",
    name: "Delamae Wilson",
    position: "School of Enviornment, Circular Ecomonmy and Sustainability ",
    email: "dwilson@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
];
export const heads = [
  {
    photo: require("../../../public/images/Leadership photos/Permilla-Farrell.jpg"),
    handle: "pfarrell",
    altText: " photo Farrell",
    name: "Permilla Farrell",
    position: "CollegeStarTT",
    email: "c@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 1111",
  },

  {
    photo: require("../../../public/images/Leadership photos/Nadine-Gonzales.jpg"),
    handle: "ngonzales",
    altText: " photo Nadine Gonzales",
    name: "Nadine Gonzales",
    position: "Creative Industries and Culture",
    email: "ngonzales@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Kirwin-Pyle.jpg"),
    handle: "kpyle",
    altText: " photo Kerwin Pyle-Williams",
    name: "Kerwin Pyle-Williams",
    position: "Criminal Justice,Human Security and Legal Studies",
    email: "kpylew@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Sophia-Edwards.jpg"),
    handle: "rsolomon",
    altText: " photo Sophia Edwards-Knox",
    name: "Sophia Edwards-Knox",
    position: "Digital Media and Communication",
    email: "lsolomond@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },

  {
    photo: require("../../../public/images/Leadership photos/Neil-Sylvester.jpg"),
    handle: "kmaharaj",
    altText: " photo Neil Sylvester",
    name: "Neil Sylvester",
    position: "Education",
    email: "kmaharaj@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
  {
    photo: require("../../../public/images/Leadership photos/Karen-Paul.jpg"),
    handle: "kpyle",
    altText: " photo Karen-Paul",
    name: "Karen Paul",
    position: "Enviornmental and Sustainability Studies",
    email: "kpylew@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 0000",
  },
  {
    photo: require("../../../public/images/Leadership photos/Anthony-Lalla.jpg"),
    handle: "rsolomon",
    altText: " photo Anthony Lalla",
    name: "Anthony Lalla",
    position: "Health and Medical Science Technologies",
    email: "lsolomond@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },

  {
    photo: require("../../../public/images/Leadership photos/Neil-Sylvester.jpg"),
    handle: "kmaharaj",
    altText: " photo Neil Sylvester",
    name: "Neil Sylvester",
    position: "Education",
    email: "kmaharaj@costaatt.edu.tt",
    phone: "1-868-625-5030 ext 3333 ",
  },
];


