import React from "react";

const leadershipdata = () => {
  return <div>leadershipdata</div>;
};

export default leadershipdata;

export const officeofpresident = [
  //   {
  //     photo: require("../../../public/images/Leadership photos/Keith-Nurse.jpeg"),
  //     handle: "knurse",
  //     altText: " photo Keith Nurse",
  //     name: "Keith Nurse",
  //     position: "President",
  //     email: "knurse@costaatt.edu.tt",
  //     phone: "1-868-625-5030 ext 0000",
  //   },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "ccharles",
    altText: " photo of Carlene Charles",
    name: "Carlene Charles",
    position: "Executive Assistant",
    email: "ccharles@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Rodney-Amar.jpg"),
    handle: "ramar",
    altText: " photo of Rodney Amar",
    name: "Rodney Amar",
    position: "Senior Project Officer",
    email: "rramar@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "mheadley",
    altText: " photo of Melissa Headley",
    name: "Melissa Headley",
    position: "Senior Project Officer",
    email: "mheadley@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Lisa-Solomon.jpg"),
    handle: "lsolomon",
    altText: " photo of Lisa Solomon",
    name: "Lisa Solomon",
    position: "Corporate Secretary",
    email: "lsolomon@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "kmaharaj",
    altText: " photo of Kavita Maharaj",
    name: "Kavita Maharaj",
    position: "Chief Internal Auditor ",
    email: "kmaharaj@costaatt.edu.tt",
  },
];
export const vps = [
  // {
  //   photo: require("../../../public/images/Leadership photos/Keith-Nurse.jpeg"),
  //   handle: "knurse",
  //   altText: " photo Keith Nurse",
  //   name: "Keith Nurse",
  //   position: "President",
  //   email: "knurse@costaatt.edu.tt",
  //   phone: "1-868-625-5030 ext 0000",
  // },
  {
    id: 1,

    photo: require("../../../public/images/Leadership photos/Naseem-Koylass.jpg"),
    handle: "ccharles",
    altText: " photo of Naseem Koylass",
    name: "Naseem Koylass",
    position: "Vice President, Academic Affairs",
    email: "nkoylass@costaatt.edu.tt",
    bio: "  Dr. Naseem Koylass was appointed to the position of Vice President, Academic Affairs effective July 1, 2022. Dr. Koylass is a long-standing member of the COSTAATT community and has held a wide range of leadership positions over the last 20 years, including department chair, campus dean and more recently, Associate Vice President, Academic Affairs. Dr Koylass has played a critical role in the College's accreditation and quality assurance activities since COSTAATT was first established in October 2000, and brings to her new position a wealth of knowledge and experience in academic and administrative leadership. As the chief administrator in the Division of Academic Affairs, she has guided and mentored the school deans, department chairs, faculty and staff and inspired them to continuously strive to achieve the institution's goals and objectives. Dr. Koylass' qualifications, which include a doctorate in Educational Leadership/Curriculum and Instruction, a Master of Science in Economics, a diploma in Educational Administration and a Bachelor of Science in Economics, ably position her to lead the Division of Academic Affairs in this next leg of COSTAATT's transformational journey to become a centre of excellence in teaching, research and service to the benefit of our diverse communities and the wider nation",
  },
  {
    id: 2,
    photo: require("../../../public/images/Leadership photos/HelenWC_small.jpg"),
    handle: "hcumberbatch",
    altText: " photo of Helen Cumberbatch",
    name: "Helen Williams-Cumberbatch",
    position: "Vice President, Student Affairs",
    email: "hcumberbatch@costaatt.edu.tt",
    bio: "Dr. Helen Williams-Cumberbatch was appointed to the position of Vice President, Student Affairs effective July 1, 2022. Prior to this appointment, she served in a range of positions at COSTAATT for over 20 years. In the last decade, she has led the College's marketing and public relations and enrolment management departments. Dr. Williams-Cumberbatch is a Fulbright scholar who completed doctoral studies at Ohio University, USA. She holds a Ph.D. in Higher Education and Student Affairs, and a MSc. in Higher Education (Enrolment Management specialization) and a BSc. in Management Studies. Her doctoral research investigated the experiences and factors that contributed to thriving among community college students in Trinidad and Tobago, and the findings of her research have informed the development of a unique model of student development for COSTAATT which will play a critical role in the positive transformation of student experiences at the College in the years ahead. Dr. Williams-Cumberbatch currently serves as 1st Vice President of the Association of Caribbean Higher Education Administrators (ACHEA). Her passion for student success positions her to lead the Division of Student Affairs in the next chapter of the COSTAATT story of transforming lives, communities and the nation…one student at a time.",
  },
  {
    id: 3,
    photo: require("../../../public/images/Leadership photos/Avenille-Matthew.jpg"),
    handle: "amatthew",
    altText: " photo of Avenille Matthew",
    name: "Avenille Matthew",
    position: "Vice President, Human Resources ",
    email: "amatthew@costaatt.edu.tt",
    bio: " Dr. Alvinelle Matthew was appointed Vice President, Human Resources Division at the College of Science,Technology and Applied Arts of the Trinidad and Tobago (COSTAATT) in January 2018.She possess a wealth of experience in developing and administering strategic human resource functions within the tertiary level sector and in various private organisations. She is passionate about human resource development and on a part-time basis engages in teaching human resource principles as an adjunct faculty. She also serves as a practicum supervisor at the University of the West Indies. She is the holder of a Doctorate in Philosophy in Social Policy with an emphasis on Human Resource Development from the University of the West Indies. Her program was partially completed at the University of Alberta, Canada through a scholarship award from the Canada-CARICOM scholarship. She also holds a Master of Arts in Human Resource Management (distinction) from the Arthur Lok Graduate School of Business and a Bachelor of Arts with majors in Human Resource Management and Psychology Counselling from the Caribbean Nazarene College",
  },
  {
    id: 4,
    photo: require("../../../public/images/Leadership photos/Lisa-Solomon.jpg"),
    handle: "rsolomon",
    altText: " photo of Lisa Solomon",
    name: "Lisa Solomon",
    position: "Corporate Secretary",
    email: "lsolomond@costaatt.edu.tt",
    bio: "Lisa Solomon is an Attorney-at-Law with close to 20 years experience, having worked as a member of various firms, in public institutions and in her own private practice. She is knowledgeable in company law and corporate governance and has worked closely with various boards of directors in the capacity of Assistant Corporate Secretary and Corporate Secretary.Ms. Solomon obtained her Bachelor of Laws degree from the University of the West Indies and the Legal Education Certificate from the Hugh Wooding Law School.",
  },
  {
    id: 5,
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "dragoonanan",
    altText: " photo of Davis Ragoonanan",
    name: "Davis Ragoonanan",
    position: "Vice President, Finance and Administration ",
    email: "dRagoonanan@costaatt.edu.tt",
    bio: "Davis Ragoonanan... ",
  },
  {
    id: 6,
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "FNicholas",
    altText: " photo of Fiola Nicholas",
    name: "Fayola Nicholas",
    position: "Vice President, Advancement ",
    email: "FNicholas@costaatt.edu.tt",
    bio: "Fayola.. ",
  },
  {


  
    id: 7,
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "Xmen",
    altText: " photo of Professor Xavier",
    name: "Professor Xavier",
    position: "Vice President, Digital Transformation  ",
    email: "pxavier@costaatt.edu.tt",
    bio: "Professior Xavier founded the X-men, a group of displaced teenagers with special powers .. ",
  },
];

export const management = [
  {
    photo: require("../../../public/images/Leadership photos/Rhonda.jpg"),
    handle: "rcumberbatch",
    altText: " photo of Rhonda Cumberbatch",
    name: "Rhonda Cumberbatch",
    position: "College Registrar",
    email: "rcumberbatch@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Dawn-Dookie.jpg"),
    handle: "ddookie",
    altText: " photo of Dawn-Dookie",
    name: "Dawn Dookie",
    position: "Director, Finance",
    email: "ddookie@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Ian-Carter.jpg"),
    handle: "icarter",
    altText: " photo of Ian Carter",
    name: "Ian Carter",
    position: "Director, Student Life & Athletics ",
    email: "icarter@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Liesel-Gransaull.jpg"),
    handle: "lbrown",
    altText: " photo of Liesel Gransaull-Brown",
    name: "Liesel Gransuall-Brown",
    position: "Director, Education Technologies & Distance Education",
    email: "lbrown@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Doodnath-Persad.jpg"),
    handle: "dpersad",
    altText: " photo of Doodnath Persad",
    name: "Dr. Doodnath Persad",
    position: "Director, Quality Assurance and Institutional Research",
    email: "dpersad@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "clstclair",
    altText: " photo of Chantale Leonard-St Clair",
    name: "Chantale Leonard-St Clair",
    position: "Director, Translation and Interpretation Services",
    email: "cstclair@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Marcia-Stanisclaus.jpg"),
    handle: "mstanisclaus",
    altText: " photo of Marcia Stanisclaus",
    name: "Marcia Stanisclaus",
    position: "Director, Planning and Employment",
    email: "mstanisclaus@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Kristed J-Herbert.jpg"),
    handle: "kherbert",
    altText: " photo of Kristed Herbert",
    name: "Kristed Herbert",
    position: "Director, Campus Services",
    email: "kherbert@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "lboodoo",
    altText: " photo of Lindsay Boodoo",
    name: "Lindsay Boodoo",
    position: "Director, Marketing and Public Relations",
    email: "lboodoo@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/darren-headley.jpeg"),
    handle: "dheadley",
    altText: " photo of Darren Headley",
    name: "Darren Headley",
    position: "Director, Technology Services",
    email: "dheadley@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Tricia-Joseph.jpg"),
    handle: "tjoseph",
    altText: " photo of Dr. Tricia Joseph",
    name: "Dr. Tricia Joseph",
    position: "Director, Health and Counselling Services",
    email: "tjoseph@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Permilla-Farrell.jpg"),
    handle: "pfarrell",
    altText: " photo of Permilla Farrell",
    name: "Permilla Farrell",
    position: "Director, CollegeStarTT",
    email: "pfarrell@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "sjbudhram",
    altText: " photo of Sabrina Julien-Budhram",
    name: "Sabrina Julien-Budhram",
    position: "Director, Procurement",
    email: "SJulienBudhram@costaatt.edu.tt",
  },
];

export const deans = [
  {
    photo: require("../../../public/images/Leadership photos/Lalita.jpg"),
    handle: "lramlal",
    altText: " photo of Lalita Ramlal-Chirkoot",
    name: "Lalita Ramlal-Chirkoot",
    position: "Dean, Workforce Enhancement and Development",
    email: "lrchirkoot@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Kyra Mc Gowan-Santana.jpg"),
    handle: "kmsantana",
    altText: " photo Kyra Mc-Gowan Santana",
    name: "Dr. Kyra Santana",
    position: "Dean, School of Business and Digital Technologies",
    email: "kmsantana@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Clarinda-Jack.jpg"),
    handle: "cjack",
    altText: " photo of Clarinda Jack",
    name: "Clarinda Jack",
    position:
      "Dean, Ken Gordon School of Communication, Creative and Digital Media",
    email: "cjack@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Anjenney-Dwarika.jpg"),
    handle: "adwarika",
    altText: " photo of Anjenny Boodoosingh-Dwarika",
    name: "Anjenny Boodoosingh-Dwarika",
    position: "Dean, School of Nursing, Health and Medical Technologies",
    email: "adwarika@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Delamae-Wilson.jpg"),
    handle: "Delamae Wilson",
    altText: " photo of Delamae Wilson",
    name: "Delamae Wilson",
    position:
      "Dean, School of Enviornment, Circular Ecomonmy and Sustainability ",
    email: "dwilson@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Neil-Sylvester.jpg"),
    handle: "nsylvester",
    altText: " photo of Neil Sylvester",
    name: "Neil Sylvester",
    position: "Dean, Liberal Arts, Education and Digital Humanities",
    email: "nsylvester@costaatt.edu.tt",
  },
];
export const heads = [
  {
    photo: require("../../../public/images/Leadership photos/Roger-Chung.jpg"),
    handle: "rchung",
    altText: " photo of Roger Chung",
    name: "Roger Chung",
    position: "ICTs and Digital Technologies",
    email: "rchung@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Heather-Dawn.jpg"),
    handle: "hdsealey",
    altText: " photo of Heather-Dawn Sealey",
    name: "Heather-Dawn Sealey",
    position: "Management and Digital Entrepreneurship",
    email: "hsealey@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Nadine-Gonzales.jpg"),
    handle: "ngonzales",
    altText: " photo of Nadine Gonzales",
    name: "Nadine Gonzales",
    position: "Creative Industries and Culture",
    email: "ngonzales@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Kirwin-Pyle.jpg"),
    handle: "kpwilliams",
    altText: " photo of Kerwin Pyle-Williams",
    name: "Kerwin Pyle-Williams",
    position: "Criminal Justice, Human Security and Legal Studies",
    email: "kpwilliams@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Sophia-Edwards.jpg"),
    handle: "seknox",
    altText: "photo of Sophia Edwards-Knox",
    name: "Sophia Edwards-Knox",
    position: "Digital Media and Communication",
    email: "sedwards@costaatt.edu.tt",
  },

  {
    photo: require("../../../public/images/Leadership photos/Karen-Paul.jpg"),
    handle: "kpaul",
    altText: " photo Karen-Paul",
    name: "Karen Paul",
    position: "Enviornmental and Sustainability Studies",
    email: "kpaul@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Anthony-Lalla.jpg"),
    handle: "alalla",
    altText: " photo of Anthony Lalla",
    name: "Dr. Anthony Lalla",
    position: "Health and Medical Science Technologies",
    email: "alalla@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/Nneka-StRose.jpg"),
    handle: "nstrose",
    altText: " photo of Dr. Nneka St Rose",
    name: "Dr. Nneka St Rose",
    position: "Social and Behavioural Sciences",
    email: "nsrose@costaatt.edu.tt",
  },
  {
    photo: require("../../../public/images/Leadership photos/deanavatar.jpg"),
    handle: "jtobas",
    altText: " photo of Jacinta Tobas",
    name: "Jacinta Tobas",
    position: "Nursing",
    email: "jtobas@costaatt.edu.tt",
  },
];
