 export const allcourses = [
   {
     photo: require("../../../images/Links/courses nursing.jpg"),
     alttext: "nursing image",
     degreeTitle: "Nursing",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
   {
     photo: require("../../../images/Links/courses business.jpg"),
     alttext: "nursing image",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
   {
     photo: require("../../../images/Links/courses music.jpg"),
     alttext: "nursing image",
     degreeTitle: "Music",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
   {
     photo: require("../../../images/Links/courses nursing.jpg"),
     alttext: "nursing image",
     degreeTitle: "Nursing",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
   {
     photo: require("../../../images/Links/courses business.jpg"),
     alttext: "nursing image",
     degreeTitle: "Nursing",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
   {
     photo: require("../../../images/Links/courses music.jpg"),
     alttext: "nursing image",
     degreeTitle: "Music",
     campus: "City ",
     fulltime: "3",
     parttime: "6",
     startdate1: "June 2023",
     startdate2: "January 2024",
     level: "Bachelors | Associate ",
   },
 ];
 
 