import React from 'react'

const allprogrammedata = () => {
  return (
    <div>allprogrammedata</div>
  )
}

export default allprogrammedata
export const coursedata = [
  {
    photo: require("../../../public/images/courses nursing.jpg"),
    alttext: "nursing image",
    degreeTitle: "Nursing",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses business.jpg"),
    alttext: "nursing image",
    degreeTitle: "Music",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses music.jpg"),
    alttext: "nursing image",
    degreeTitle: "Music",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses nursing.jpg"),
    alttext: "nursing image",
    degreeTitle: "Nursing",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses business.jpg"),
    alttext: "nursing image",
    degreeTitle: "Nursing",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses music.jpg"),
    alttext: "nursing image",
    degreeTitle: "Music",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses nursing.jpg"),
    alttext: "nursing image",
    degreeTitle: "Nursing",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses business.jpg"),
    alttext: "nursing image",
    degreeTitle: "Nursing",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
  {
    photo: require("../../../public/images/courses music.jpg"),
    alttext: "nursing image",
    degreeTitle: "Music",
    campus: "City ",
    fulltime: "3",
    parttime: "6",
    startdate1: "June 2023",
    startdate2: "January 2024",
    level: "Bachelors | Associate ",
  },
];
