import React from 'react'

const collegecoredata = () => {
  return (
    <div>collegecoredata</div>
  )
}

export default collegecoredata

export const collegecore = [
  {
    discipline: 'Humanities ',
    courseCode: 'ANTH 250',
    courseTitle: 'Caribbean Anthropology',
    credits: '3',
    prerequisite: 'None',
  },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'COMM 108',
  //   courseTitle: 'Oral Presentation Skills',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'COMM 118',
  //   courseTitle: 'Communication in the Workplace',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'COMM 119',
  //   courseTitle: 'Advanced Grammar for Office Professionals',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'COMM 140',
  //   courseTitle: 'Speech Writing',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'PUBR 221',
  //   courseTitle: 'Image, Etiquette and Protocol',
  //   credits: '2',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'CRIM 125',
  //   courseTitle: 'Introduction to Criminal Justice',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'CLTR 120',
  //   courseTitle: 'Introduction to the Culture of Trinidad and Tobago',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ECCE 100',
  //   courseTitle: 'Introduction to the World of the Learner',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'EDUC 124',
  //   courseTitle: 'Sign Language 1',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'EDUC 125',
  //   courseTitle: 'Advanced Sign Language for Educators',
  //   credits: '3',
  //   prerequisite: 'EDUC 124',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ECCE 150',
  //   courseTitle: 'Child Development',
  //   credits: '3',
  //   prerequisite: 'WRIT 117',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ECCE 120',
  //   courseTitle: 'Introduction to Developmental Disabilities',
  //   credits: '3',
  //   prerequisite: 'ECCE 150',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ECCE 211',
  //   courseTitle: 'Instructional Technology for Early Learners',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'FILM 290',
  //   courseTitle: 'Introduction to Video Production',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'FILM 261',
  //   courseTitle: 'Single Camera Production',
  //   credits: '3',
  //   prerequisite: 'FILM 290',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ARTS 120',
  //   courseTitle: 'Survey of Art History',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'GRDE 123',
  //   courseTitle: 'Introduction to Drawing and Painting',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'GRDE 127',
  //   courseTitle: 'Digital Communication Design',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'GRDE 129',
  //   courseTitle: 'Introduction to Graphic Design',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'HIST 210',
  //   courseTitle: 'History of Trinidad and Tobago',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'HIST 225',
  //   courseTitle: 'Latin American History 1',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'JOUR 135',
  //   courseTitle: 'Photojournalism',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'SPAN 100',
  //   courseTitle: 'Introduction to Spanish',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'PORT 150',
  //   courseTitle: 'Brazilian Culture and Language I',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'SPAN 140',
  //   courseTitle: 'Spanish Language I',
  //   credits: '4',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'LAWW 130',
  //   courseTitle: 'Caribbean Legal Systems',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'LAWW 133',
  //   courseTitle: 'Law and Community',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'LIBS 130',
  //   courseTitle: 'Fundamental Research Skills',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'RCMT 150',
  //   courseTitle: 'Introduction to Records Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ENGL 121',
  //   courseTitle: 'Introduction to Poetry',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ENGL 122',
  //   courseTitle: 'Introduction to Drama',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ENGL 123',
  //   courseTitle: 'Introduction to Prose Fiction',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ENGL 131',
  //   courseTitle: 'Oral Literatures',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'ENGL 270',
  //   courseTitle: 'Creative Writing',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSC 120',
  //   courseTitle: 'Introduction to the History of Western Music',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSV 151',
  //   courseTitle: 'Major Performing Ensemble I - Voice',
  //   credits: '1',
  //   prerequisite: 'Audition',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSJ 151',
  //   courseTitle: 'Major Performing Ensemble I - Pan',
  //   credits: '1',
  //   prerequisite: 'Audition',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSG 313',
  //   courseTitle: 'Guitar Accompaniment',
  //   credits: '2',
  //   prerequisite: 'All students must have an instrument',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSC 312',
  //   courseTitle: 'Introduction to Music Therapy',
  //   credits: '2',
  //   prerequisite: 'WRIT 117',
  // },
  // {
  //   discipline: 'Humanities ',
  //   courseCode: 'MUSC 404',
  //   courseTitle: 'Acoustics/Pan Technology',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 117',
  //   courseTitle: 'College Algebra',
  //   credits: '3',
  //   prerequisite: 'MATH 093',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 119',
  //   courseTitle: 'Finite Mathematics',
  //   credits: '3',
  //   prerequisite: 'MATH 117',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 116',
  //   courseTitle: 'Contemporary College Mathematics',
  //   credits: '3',
  //   prerequisite: 'MATH 092',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 111',
  //   courseTitle: 'Geometry',
  //   credits: '3',
  //   prerequisite: 'MATH 093',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 126',
  //   courseTitle: 'Introduction to Financial Mathematics',
  //   credits: '3',
  //   prerequisite: 'MATH 118',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'MATH 175',
  //   courseTitle: 'Mathematics for Elementary School Teachers',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'STAT 120',
  //   courseTitle: 'Fundamentals of Statistics',
  //   credits: '3',
  //   prerequisite: 'MATH 093, or MATH 092 and a 100-level mathematics course',
  // },
  // {
  //   discipline: 'Mathematics',
  //   courseCode: 'STAT 121',
  //   courseTitle: 'Introduction to Inferential Statistics',
  //   credits: '3',
  //   prerequisite: 'STAT 120',
  // },
  // {
  //   discipline: 'Information Technology',
  //   courseCode: 'ITEC 121',
  //   courseTitle: 'Productivity Tools',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Information Technology',
  //   courseCode: 'ITEC 240',
  //   courseTitle: 'Web Page Design',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Information Technology',
  //   courseCode: 'ITEC 229',
  //   courseTitle: 'Human Computer Interface Design',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Information Technology',
  //   courseCode: 'ITEC 120',
  //   courseTitle: 'Introduction to Computer Hardware',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Information Technology',
  //   courseCode: 'GISY 172',
  //   courseTitle: 'Intro to Geographic Information Systems',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'ACCT 126',
  //   courseTitle: 'Fundamentals of Accounting',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'ADMN 310',
  //   courseTitle: 'Introduction to Public Administration',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'BUSI 203',
  //   courseTitle: 'Leadership and Ethics',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MGMT 105',
  //   courseTitle: 'Introduction to Supervisory Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MGMT 108',
  //   courseTitle: 'Introduction to Organisational Behaviour',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MGMT 125',
  //   courseTitle: 'Principles of Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MGMT 200',
  //   courseTitle: 'Event Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MGMT 225',
  //   courseTitle: 'Procurement and Inventory Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'ECON 110',
  //   courseTitle: 'Introduction to General Economics',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'ENTP 210',
  //   courseTitle: 'Fundamentals of Entrepreneurship',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'FINC 205',
  //   courseTitle: 'Financial Management',
  //   credits: '3',
  //   prerequisite: 'ACTT 126',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'GEOG 121',
  //   courseTitle: 'Introduction to Geography ',
  //   credits: '3',
  //   prerequisite: 'CXC Math/English and or any related pre-college',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'HURM 117',
  //   courseTitle: 'Conflict Resolution and Mediation',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'HURM 120',
  //   courseTitle: 'Introduction to Industrial Relations',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'HURM 310',
  //   courseTitle: 'Human Resource Management',
  //   credits: '3',
  //   prerequisite: 'MGMT 125',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'LAST 120',
  //   courseTitle: 'Introduction to Latin American Studies',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MKTG 125',
  //   courseTitle: 'Customer Service Fundamentals',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Social Sciences',
  //   courseCode: 'MKTG 290',
  //   courseTitle: 'Digital Marketing and Communications',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Behavioural Science',
  //   courseCode: 'PSYC 103',
  //   courseTitle: 'Understanding Human Behaviour and Diversity',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Behavioural Science',
  //   courseCode: 'RELI 205',
  //   courseTitle: 'Comparative Religion',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Behavioural Science',
  //   courseCode: 'SOCI 102',
  //   courseTitle: 'Introduction to the Study of Society',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Behavioural Science',
  //   courseCode: 'SOBE 135',
  //   courseTitle: 'Understanding Culture, Communication and Conflict',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'ENVH 102',
  //   courseTitle: 'World Issues in Public Health',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'ENVS 121',
  //   courseTitle: 'Environmental Issues and Sustainability',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'ENVS 160',
  //   courseTitle: 'Environmental Studies I',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'ENVS 215',
  //   courseTitle: 'Disaster Management',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'HLED 100',
  //   courseTitle: 'Intro to OSH and First Aid',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'OSHE 123',
  //   courseTitle: 'Introduction to Occupational Safety and Health',
  //   credits: '3',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'SCIE 121',
  //   courseTitle: 'Foundations of Natural Science',
  //   credits: '3',
  //   prerequisite: 'CXC Math/English and or any related pre-college',
  // },
  // {
  //   discipline: 'Science',
  //   courseCode: 'SCIE 201',
  //   courseTitle: 'Intro to Contemporary Issues in Sciences',
  //   credits: '1',
  //   prerequisite: 'CXC Math/English and or any related pre-college',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'TOUR 101',
  //   courseTitle: 'Tour Guiding',
  //   credits: '4',
  //   prerequisite: 'Any 3 CXC passes',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'OFAD 101',
  //   courseTitle: 'Keyboarding I',
  //   credits: '2',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'OFAD 102',
  //   courseTitle: 'Keyboarding II',
  //   credits: '2',
  //   prerequisite: 'OFAD101',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'OFAD 103',
  //   courseTitle: 'Keyboarding III',
  //   credits: '3',
  //   prerequisite: 'OFAD102',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'COMM 100',
  //   courseTitle: 'Technical Report Writing Workshop',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
  // {
  //   discipline: 'Continuing Education',
  //   courseCode: 'SOBE 103',
  //   courseTitle: 'Conflict Management Workshop',
  //   credits: '1',
  //   prerequisite: 'None',
  // },
];
