export const supportDocA = [
  {
    Nationality: "TT Nationals",
    Valid_ID: "Yes",
    Valid_PassPort: "",
    Birth_Certificate: "Yes",
    Academic_Certificate: "Yes",
  },
  {
    Nationality: "Non-Nationals",
    Valid_ID: "",
    Valid_PassPort: "Yes",
    Birth_Certificate: "",
    Academic_Certificate: "Yes",
  },
];

export const supportDocB = [
  {
    Programme: "General Nursing (AAS,BSc)",
    References: "Yes",
    Police_Cert: "Yes",
    Council: "Yes",
    Statement: "",
  },
  {
    Programme: "Psychiatric Nursing (AAS,BSc)",
    References: "Yes",
    Police_Cert: "Yes",
    Council: "Yes",
    Statement: "",
  },
  {
    Programme: "Midwifery (BSc)",
    References: "Yes",
    Police_Cert: "Yes",
    Council: "Yes",
    Statement: "",
  },
  {
    Programme: "Medical Laboratory Technology(AAS, BSC",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "",
  },
  {
    Programme: "Medical Ulttasound (AdvDip)",
    References: "",
    Police_Cert: "",
    Council: "",
    Statement: "Yes",
  },
  {
    Programme: "Radiography (BSc)",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "Yes",
  },
  {
    Programme: "Environmental Health (AAS, BSc)",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "",
  },
  {
    Programme: "Occupational Safety and Health(AAS, BSc)",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "",
  },
  {
    Programme: "Social Work (BSW)",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "",
  },
  {
    Programme: "Early Childhood Care and Education (BA)",
    References: "Yes",
    Police_Cert: "",
    Council: "",
    Statement: "Yes",
  },
];

export const institutionFees = [
  {
    Fees: "Applications: Paper-based",
    Citizens: "$25.00",
    Caricom: "$25.00",
    International: "$25.00",
    Per: "Application",
  },
  {
    Fees: "Re-Admission: Paper-based",
    Citizens: "$10.00",
    Caricom: "$10.00",
    International: "$10.00",
    Per: "Application",
  },
  {
    Fees: "Applications: Online",
    Citizens: "Free",
    Caricom: "Free",
    International: "Free",
    Per: "Application",
  },
  {
    Fees: "Registration",
    Citizens: "	$80.00",
    Caricom: "$80.00",
    International: "$80.00",
    Per: "Semester",
  },
  {
    Fees: "Tuition",
    Citizens: "$300.00",
    Caricom: "$400.00",
    International: "$750.00",
    Per: "Credit",
  },
  {
    Fees: "Administrative Fee",
    Citizens: "$100.00",
    Caricom: "$100.00",
    International: "$100.00",
    Per: "	Semester",
  },
  {
    Fees: "Technology",
    Citizens: "$100.00",
    Caricom: "$100.00",
    International: "$100.00",
    Per: "	Semester",
  },
  {
    Fees: "Student Insurance",
    Citizens: "$30.00",
    Caricom: "$30.00",
    International: "$30.00",
    Per: "Annum",
  },
];

export const dptOfManagementFees = [
  {
    Programme: "AAS Business Administration",
    Total_Credit: "	61",
    National: "	$18,300",
    CARICOM: "$24,400",
    International: "	$45,750",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Mgmt. With Accounting",
    Total_Credit: "	61",
    National: "	$18,300",
    CARICOM: "$24,400",
    International: "	$45,750",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Business Administration",
    Total_Credit: "	61",
    National: "	$18,300",
    CARICOM: "$24,400",
    International: "	$45,750",
    GATE: "	Yes",
  },
  {
    Programme: "AS Mgmt. Studies for the Protective Services",
    Total_Credit: "	63",
    National: "	$18,900",
    CARICOM: "	N/A",
    International: "	N/A",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Office Administration",
    Total_Credit: "	61",
    National: "	$18,300",
    CARICOM: "$25,200",
    International: "$45,750",
    GATE: "	Yes",
  },
  {
    Programme: "BA Accounting",
    Total_Credit: "120",
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "	Yes",
  },
  {
    Programme: "BA Financial Mgmt",
    Total_Credit: "120",
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "	Yes",
  },
  {
    Programme: "BBA Human Resource Mgmt.",
    Total_Credit: "122",
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$91,500",
    GATE: "	Yes",
  },
  {
    Programme: "BBA Mgmt. & Entrepreneurship",
    Total_Credit: "120",
    National: "	$36,000",
    CARICOM: "	$48,000",
    International: "$90,000",
    GATE: "	Yes",
  },
  {
    Programme: "BBA Marketing",
    Total_Credit: "	117",
    National: "		$35,100",
    CARICOM: "$46,800",
    International: "$87,750",
    GATE: "	Yes",
  },
  {
    Programme: "Diploma - Supervisory Mgmt.",
    Total_Credit: "	36",
    National: "$10,800",
    CARICOM: "$14,400",
    International: "$27,000",
    GATE: "	Yes",
  },
  {
    Programme: "Certificate - Supervisory Mgmt.",
    Total_Credit: "18",
    National: "$5,400",
    CARICOM: "$7,200",
    International: "$13,500",
    GATE: "	Yes",
  },
];
export const deptOfInformation = [
  {
    Programme: "AAS Library Science",
    Total_Credit: "	61",
    National: "	$18,300",
    CARICOM: "$24,400",
    International: "	$45,750",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Information Technology",
    Total_Credit: "64",
    National: "	$19,200",
    CARICOM: "$$25,600",
    International: "	$48,000",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Info. Systems Development",
    Total_Credit: "64",
    National: "	$19,200",
    CARICOM: "$$25,600",
    International: "	$48,000",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Operating Systems Development",
    Total_Credit: "64",
    National: "	$19,200",
    CARICOM: "$$25,600",
    International: "	$48,000",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Computer Info. Systems",
    Total_Credit: "121",
    National: "	$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Networking",
    Total_Credit: "121",
    National: "	$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Internet Technology",
    Total_Credit: "121",
    National: "	$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Information Technology",
    Total_Credit: "121",
    National: "	$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Information and Library Science",
    Total_Credit: "121",
    National: "	$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "Certificate - Records Mgmt.",
    Total_Credit: "		20",
    National: "	$6,000",
    CARICOM: "$8,000",
    International: "	$15,000",
    GATE: "	Yes",
  },
  {
    Programme: "Certificate - Records Mgmt. for Public Sector",
    Total_Credit: "32",
    National: "$6,900",
    CARICOM: "$	$12,800",
    International: "	$24,000",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Library Science",
    Total_Credit: "16",
    National: "	$4,800",
    CARICOM: "$6,400",
    International: "	$12,000",
    GATE: "	Yes",
  },
];

export const deptOfNursingFees = [
  {
    Programme: "AAS Basic Psychiatric Nursing",
    Total_Credit: "91",
    National: "$27,300",
    CARICOM: "	$36,400",
    International: "$68,250",
    GATE: "	Yes",
  },
  {
    Programme: "AAS Basic General Nursing",
    Total_Credit: "85",
    National: "$25,500",
    CARICOM: "$34,000",
    International: "$63,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Psychiatric Nursing",
    Total_Credit: "127",
    National: "$38,100",
    CARICOM: "$50,800",
    International: "$95,250",
    GATE: "	Yes",
  },
  {
    Programme: "BSc General Nursing",
    Total_Credit: "124",
    National: "$37,200",
    CARICOM: "$49,600",
    International: "$93,000",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Midwifery (Direct Entry)",
    Total_Credit: "123",
    National: "$36,900",
    CARICOM: "$49,200",
    International: "$92,250",
    GATE: "	Yes",
  },
  {
    Programme: "Post Graduate Dip. - District Health Visiting",
    Total_Credit: "35",
    National: "$17,500",
    CARICOM: "$21,000",
    International: "$26,250",
    GATE: "No",
  },
];

export const deptOfHealth = [
  {
    Programme: "AAS Medical Laboratory Technology",
    Total_Credit: "73",
    National: "$21,900",
    CARICOM: "$29,2000",
    International: "$54,750",
    GATE: "No",
  },
  {
    Programme: "BSc Medical Laboratory Technology",
    Total_Credit: "121",
    National: "$36,300",
    CARICOM: "$48,400",
    International: "	$90,750",
    GATE: "	Yes",
  },
  {
    Programme: "BSc Radiography",
    Total_Credit: "141",
    National: "$42,300",
    CARICOM: "$56,400",
    International: "$105,750",
    GATE: "Yes",
  },

  {
    Programme: "Certificate - Phlebotomy",
    Total_Credit: "15",
    National: "$5,000",
    CARICOM: "	N/A",
    International: "	N/A",
    GATE: "No",
  },
  {
    Programme: "Certificate - Pharmacy Assistance",
    Total_Credit: "27",
    National: "	$8,100",
    CARICOM: "$10,800",
    International: "$20,250",
    GATE: "Yes",
  },
];

export const dptOfNatSci = [
  {
    Programme: "BSc Biology/Pre-Med",
    Total_Credit: "120",
    National: "	$36,000",
    CARICOM: "	$48,000",
    International: "	$90,000",
    GATE: "Yes",
  },
  {
    Programme: "Certificate - Pharmacy Assistance",
    Total_Credit: "27",
    National: "$18,600",
    CARICOM: "$24,800",
    International: "	$46,500",
    GATE: "Yes",
  },
  {
    Programme: "AS Chemistry",
    Total_Credit: "	62",
    National: "$18,600",
    CARICOM: "$24,800",
    International: "$46,500",
    GATE: "Yes",
  },
];

export const dptOfEnvStud = [
  {
    Programme: "BSc Environmental Health",
    Total_Credit: "	122",
    National: "$36,600",
    CARICOM: "$48,800",
    International: "	$91,500",
    GATE: "Yes",
  },
  {
    Programme: "BSc Occupational Safety and Health",
    Total_Credit: "	121",
    National: "$36,300",
    CARICOM: "	$48,400",
    International: "$90,750",
    GATE: "Yes",
  },
  {
    Programme: "BSc Water and Wastewater Mgmt.",
    Total_Credit: "	126",
    National: "$37,800",
    CARICOM: "	$94,500",
    International: "$46,500",
    GATE: "Yes",
  },
  {
    Programme: "AAS Environmental Health",
    Total_Credit: "67",
    National: "$20,100",
    CARICOM: "$26,800",
    International: "$50,250",
    GATE: "Yes",
  },
  {
    Programme: "AAS Environmental Management",
    Total_Credit: "	66",
    National: "$19,800",
    CARICOM: "$26,400",
    International: "	$49,500",
    GATE: "Yes",
  },
  {
    Programme: "AAS Occupational Safety and Health",
    Total_Credit: "	67",
    National: "$20,100",
    CARICOM: "$	$26,800",
    International: "$50,250",
    GATE: "Yes",
  },
  {
    Programme: "AAS Geographic Information Systems",
    Total_Credit: "60",
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "AAS Water and Wastewater Mgmt.",
    Total_Credit: "69",
    National: "$20,700",
    CARICOM: "$27,600",
    International: "	$51,750",
    GATE: "Yes",
  },
];
export const schoolOfCrimJus = [
  {
    Programme: "AAS Criminal Justice",
    Total_Credit: "63",
    National: "	$18,900",
    CARICOM: "	$25,200",
    International: "	$47,250",
    GATE: "Yes",
  },
  {
    Programme: "BA Criminal Justice",
    Total_Credit: "121",
    National: "$36,300",
    CARICOM: "	$48,400",
    International: "$90,750",
    GATE: "Yes",
  },
  {
    Programme: "Certificate – Criminal Justice",
    Total_Credit: "24",
    National: "$7,200",
    CARICOM: "$9,600",
    International: "	$18,000",
    GATE: "Yes",
  },
];

export const dptOfMath = [
  {
    Programme: "AS Mathematics",
    Total_Credit: "120",
    National: "	$18,000",
    CARICOM: "$24,000",
    International: "		$45,000",
    GATE: "Yes",
  },
  {
    Programme: "BSc Mathematics",
    Total_Credit: "24",
    National: "$36,000",
    CARICOM: "$48,000",
    International: "	$90,000",
    GATE: "Yes",
  },
];

export const officeOfDean = [
  {
    Programme: "AA Early Childhood Care and Education",
    Total_Credit: "60",
    National: "$18,000",
    CARICOM: "	$24,000",
    International: "	$45,000",
    GATE: "	No",
  },
  {
    Programme: "BA Early Childhood Care and Education",
    Total_Credit: 120,
    National: "$36,000",
    CARICOM: "$48,000",
    International: "	$90,000",
    GATE: "Yes",
  },
  {
    Programme: "Certificate – Early Childhood Care and Education",
    Total_Credit: 25,
    National: "$7,500",
    CARICOM: "$10,000",
    International: "$18,750",
    GATE: "Yes",
  },
];

export const dptOfSocBehSci = [
  {
    Programme: "AAS Sociology",
    Total_Credit: "63",
    National: "	$18,900",
    CARICOM: "$25,200",
    International: "$47,250",
    GATE: "Yes",
  },
  {
    Programme: "AAS Social Work",
    Total_Credit: "	60",
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "AA Psychology",
    Total_Credit: "	60",
    National: "$18,000",
    CARICOM: "$24,000",
    International: "	$45,000",
    GATE: "Yes",
  },
  {
    Programme: "BSW Social Work",
    Total_Credit: "120",
    National: "$36,000",
    CARICOM: "	$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BSc Psychology",
    Total_Credit: "120",
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BSc Applied Psychology",
    Total_Credit: "	135",
    National: "	$40,500",
    CARICOM: "$54,000",
    International: "	$101,250",
    GATE: "Yes",
  },
  {
    Programme: "Certificate – Family and Community Studies",
    Total_Credit: "20",
    National: "$6,000",
    CARICOM: "$8,000",
    International: "$15,000",
    GATE: "Yes",
  },
];
export const deptOfLang = [
  {
    Programme: "AA Literatures in English",
    Total_Credit: 60,
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "AA Spanish",
    Total_Credit: 63,
    National: "$18,900",
    CARICOM: "$25,200",
    International: "$47,250",
    GATE: "Yes",
  },
  {
    Programme: "AAS Foreign Languages for Business: Spanish",
    Total_Credit: 63,
    National: "$18,300",
    CARICOM: "$25,200",
    International: "$47,250",
    GATE: "Yes",
  },
  {
    Programme: "BA Literature & Communication",
    Total_Credit: 120,
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BA Latin American Studies",
    Total_Credit: 120,
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BA Spanish for Business",
    Total_Credit: 125,
    National: "$37,500",
    CARICOM: "$50,000",
    International: "$93,750",
    GATE: "Yes",
  },
];

export const dptofFineArts = [
  {
    Programme: "AAS Performing Arts: Music",
    Total_Credit: 65,
    National: "$19,500",
    CARICOM: "$26,000",
    International: "$48,750",
    GATE: "Yes",
  },
  {
    Programme: "BM Music Performance",
    Total_Credit: 124,
    National: "$37,200",
    CARICOM: "$49,600",
    International: "$93,000",
    GATE: "Yes",
  },
  {
    Programme: "BM Music Education",
    Total_Credit: 124,
    National: "$37,200",
    CARICOM: "$49,600",
    International: "$93,000",
    GATE: "Yes",
  },
  {
    Programme: "Certificate – Music Performance",
    Total_Credit: 21,
    National: "$6,300",
    CARICOM: "$8,400",
    International: "$15,750",
    GATE: "Yes",
  },
];

export const comensentoryProg = [
  {
    Programme: "Certificate - COMPASS",
    Total_Credit: "45 (max.)",
    National: "	$13,500 (maximum estimation)",
    CARICOM: "$18,000",
    International: "$33,750",
    GATE: "Yes",
  },
];

export const continuingEduc = [
  {
    Programme: "AAS CAT Reporting",
    Total_Credit: 61,
    National: "$18,300",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Accounting Fundamentals",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Accounting Systems and Apps",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Administrative Office Mgmt",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Adv Conversational Spanish",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Adv Gram Office Professionals",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advance Dip. - Food Inspection",
    Total_Credit: 28,
    National: "$11,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advance Dip. - Port Health",
    Total_Credit: 28,
    National: "$11,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advance Dip. - Vector Control",
    Total_Credit: 33,
    National: "$13,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advanced Makeup Artistry",
    Total_Credit: 0,
    National: "$750",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advanced MS Excel",
    Total_Credit: 3,
    National: "$450",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advanced MS PowerPoint",
    Total_Credit: 3,
    National: "$400",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Advanced MS Word",
    Total_Credit: 3,
    National: "$400",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Basic Tour Guiding",
    Total_Credit: 3,
    National: "$1,000",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Basic Web Page Design",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Broadcast Newswriting",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Business Communication",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Certificate - Court Transcription",
    Total_Credit: 28,
    National: "$8,400",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "Yes",
  },
  {
    Programme: "Certificate - Diabetes Educator",
    Total_Credit: "N/A",
    National: "$15,000",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Child Development",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Commercial & Indus Info Sys",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Computer Foundation Tools",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Computer Literacy",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Constitutional Law",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Copywriting",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "COVID-19 Compliance & Readiness",
    Total_Credit: "N/A",
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Crime and the Media",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Criminal Law",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme:
      "Critical Reading and Writing for Journalism and Communication Majors",
    Total_Credit: 4,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Cust Serv Fund - SMEs in COVID",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Customer Service Fundamentals",
    Total_Credit: 3,
    National: "$450",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Digital Communication Design",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Digital Marketing",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Digital Photography & Animation for Advertising",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Digital Photography",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Digital Voice Transcription",
    Total_Credit: "N/A",
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Disaster Preparedness and Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Electronic Commerce",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Ethics in Journalism and PR",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Event Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Events Photography",
    Total_Credit: 3,
    National: "$750",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "First Aid and CPR Certification",
    Total_Credit: 3,
    National: "$850",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Food Quality Assurance",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Fundamentals of Customer Service",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Fundamentals of Import&Export",
    Total_Credit: "N/A",
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Fundamentals of Reporting",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Fundamentals of Selling",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Geographic Information Systems",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Health Fitness Safety in ECCE",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Henna/Mehndi Design",
    Total_Credit: 0,
    National: "$450",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Human & Comp Interface Design",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Human Resource Fundamentals",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Image Manipulation",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Image, Etiquette and Protocol",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Import and Export Management",
    Total_Credit: "N/A",
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Industrial Relations",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Infirmary Care",
    Total_Credit: 30,
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Information Systems Project Management",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Instructional Technology for PreSchool Teachers",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Drawing and Painting",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Mass Communication",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Computer Hardware",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Criminal Justice",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Database Programming",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Desktop Publishing & Presentation",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Film",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Motion Graphics",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Networks",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Occupational Safety and Health",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Photojournalism",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Procurement",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Programming",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Project Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Public Sector Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Records Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Sign Language",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Strategic Public Relations",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Supervisory Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Video Production",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Word Processing",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Events Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Graphic Design",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Nail Art",
    Total_Credit: 0,
    National: "$500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Introduction to Spanish",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    "Make-up Artistry": {
      Programme: "Make-up Artistry",
      Total_Credit: 0,
      National: "$500",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Maths for Elementary School Teachers": {
      Programme: "Maths for Elementary School Teachers",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Microsoft Outlook": {
      Programme: "Microsoft Outlook",
      Total_Credit: 3,
      National: "$200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Microsoft Teams": {
      Programme: "Microsoft Teams",
      Total_Credit: 3,
      National: "$200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Minute Taking": {
      Programme: "Minute Taking",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Office Administration": {
      Programme: "Office Administration",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Oral Presentation Skills": {
      Programme: "Oral Presentation Skills",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Org and Mgmt of an ECCE Centre": {
      Programme: "Org and Mgmt of an ECCE Centre",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    "Organizational Behaviour": {
      Programme: "Organizational Behaviour",
      Total_Credit: 3,
      National: "$1,200",
      CARICOM: "N/A",
      International: "N/A",
      GATE: "No",
    },
    Programme: "OSH Risk Assessment in COVID",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },

  {
    Programme: "Photoshop for Photographers",
    Total_Credit: 0,
    National: "$900",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Post Graduate Dip. - Forensic Auditing and Investigation",
    Total_Credit: 31,
    National: "$15,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Post Graduate Dip. – International Trade and Commerce",
    Total_Credit: 33,
    National: "$16,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Principles of Design",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Principles of Management",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Productivity Tools",
    Total_Credit: 3,
    National: "$1,500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Script Writing I",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Script Writing II",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Sign Language",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Single Camera Production",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "SME Diversification in COVID",
    Total_Credit: 3,
    National: "$500",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Social Media Communications",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Social Media for Adults",
    Total_Credit: 0,
    National: "$350",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Social Media Literacy",
    Total_Credit: 0,
    National: "$300",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Spanish for Communication II",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Speech Writing",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Survey of Art History",
    Total_Credit: 3,
    National: "$700",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Systems Analysis and Design",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Teacher Training",
    Total_Credit: "N/A",
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Tour Guiding",
    Total_Credit: 4,
    National: "Customized/contract training",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Typing and Shorthand",
    Total_Credit: 3,
    National: "$2,650",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Typography I",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Underst Human Communication",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Underst Young Children's Beh",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Understanding Personal and Business Taxation",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Vector Graphics",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Video and Film Editing 1",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Visual Thinking and Advertising Concepts",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
  {
    Programme: "Voice Presentation",
    Total_Credit: 3,
    National: "$1,200",
    CARICOM: "N/A",
    International: "N/A",
    GATE: "No",
  },
];
export const deptOFJour = [
  {
    Programme: "AA Journalism",
    Total_Credit: 60,
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "AAS Journalism / Public Relations",
    Total_Credit: 60,
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "AA Film & Video Productions",
    Total_Credit: 60,
    National: "$18,000",
    CARICOM: "$24,000",
    International: "$45,000",
    GATE: "Yes",
  },
  {
    Programme: "BA Journalism",
    Total_Credit: 121,
    National: "$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "Yes",
  },
  {
    Programme: "BA Film & Video Productions",
    Total_Credit: 121,
    National: "$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "Yes",
  },
  {
    Programme: "Certificate – Film and Video Production",
    Total_Credit: 15,
    National: "$4,500",
    CARICOM: "$6,000",
    International: "$11,250",
    GATE: "No",
  },
  {
    Programme: "Certificate - Journalism",
    Total_Credit: 12,
    National: "$3,600",
    CARICOM: "$4,800",
    International: "$9,000",
    GATE: "No",
  },
  {
    Programme: "Certificate - Public Relations",
    Total_Credit: 14,
    National: "$4,200",
    CARICOM: "$5,600",
    International: "$10,500",
    GATE: "No",
  },
  {
    Programme: "Diploma – Film and Video Production",
    Total_Credit: 30,
    National: "$9,000",
    CARICOM: "$12,000",
    International: "$22,500",
    GATE: "Yes",
  },
];

export const deptOfComm = [
  {
    Programme: "AAS Advertising and Promotions",
    Total_Credit: 66,
    National: "$19,800",
    CARICOM: "$26,400",
    International: "$49,500",
    GATE: "Yes",
  },
  {
    Programme: "AAS Graphic Design",
    Total_Credit: 62,
    National: "$18,600",
    CARICOM: "$24,800",
    International: "$46,500",
    GATE: "Yes",
  },
  {
    Programme: "BA Advertising and Promotions",
    Total_Credit: 120,
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BA Graphic Design",
    Total_Credit: 120,
    National: "$36,000",
    CARICOM: "$48,000",
    International: "$90,000",
    GATE: "Yes",
  },
  {
    Programme: "BA Mass Communications",
    Total_Credit: 121,
    National: "$36,300",
    CARICOM: "$48,400",
    International: "$90,750",
    GATE: "Yes",
  },
  {
    Programme: "Certificate - Advertising and Promotions",
    Total_Credit: 15,
    National: "$4,500",
    CARICOM: "$6,000",
    International: "$11,250",
    GATE: "No",
  },
  {
    Programme: "Certificate - Essential Skills for the Work Place",
    Total_Credit: 15,
    National: "$4,500",
    CARICOM: "$6,000",
    International: "$11,250",
    GATE: "No",
  },
  {
    Programme: "Certificate - Graphic Design",
    Total_Credit: 15,
    National: "$4,500",
    CARICOM: "$6,000",
    International: "$11,250",
    GATE: "No",
  },
  {
    Programme: "Certificate - Photography and Video",
    Total_Credit: 15,
    National: "$4,500",
    CARICOM: "$6,000",
    International: "$11,250",
    GATE: "No",
  },
  {
    Programme: "Executive Dip. - Advertising and Promotions",
    Total_Credit: 30,
    National: "$9,000",
    CARICOM: "$12,000",
    International: "$22,500",
    GATE: "Yes",
  },
];
